name: Linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['5.5', '5.6', '7.0', '7.1', '7.2']
      fail-fast: false

    name: PHP ${{ matrix.php-versions }} on ubuntu-latest

    steps:
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: ${{ matrix.coverage }}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php-versions }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run phpcs
        run: vendor/bin/phpcs --standard=phpcs.xml classes tests

      - name: Run tests
        run: vendor/bin/atoum --test-ext

